title: 'arcshaun.github.io'
description: "I am starting to hate this shit"
baseurl: "home"
url: "https://arcshaun.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark
git 
footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
